<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>ch.rasc</groupId>
    <artifactId>wamp2spring-parent</artifactId>
    <version>4.0.2-SNAPSHOT</version>
  </parent>

  <artifactId>wamp2spring-security-servlet</artifactId>

  <name>Integration of wamp2spring with Spring Security Servlet</name>
  <description>Integration of wamp2spring with Spring Security Servlet</description>

  <properties>
    <main.basedir>${project.parent.basedir}</main.basedir>
  </properties>

  <dependencies>

    <dependency>
      <groupId>ch.rasc</groupId>
      <artifactId>wamp2spring-security-core</artifactId>
      <version>${project.version}</version>
    </dependency>

    <dependency>
      <groupId>ch.rasc</groupId>
      <artifactId>wamp2spring-servlet</artifactId>
      <version>${project.version}</version>
    </dependency>

    <dependency>
      <groupId>com.google.code.findbugs</groupId>
      <artifactId>jsr305</artifactId>
      <version>3.0.2</version>
      <scope>provided</scope>
    </dependency>

  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.16.0</version>
        <configuration>
          <release>17</release>
          <testRelease>17</testRelease>
          <encoding>UTF-8</encoding>
          <parameters>true</parameters>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>3.12.0</version>
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <goals>
              <goal>jar</goal>
            </goals>
            <configuration>
              <sourcepath>${project.build.sourceDirectory}${path.separator}../wamp2spring-core/src/main/java</sourcepath>
              <failOnError>false</failOnError>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
